[[pages]]
path = "./src/server.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "./src/pages/upload.py"
name = "Upload Data"
icon = "ğŸ—„ï¸"

[[pages]]
path = "./src/pages/eda.py"
name = "EDA"
icon = "ğŸ“Š"

[[pages]]
path = "./src/pages/automl.py"
name = "AutoML Training"
icon = "ğŸ¤–"

[[pages]]
path = "./src/pages/preview.py"
name = "Predictions"
icon = "ğŸ”"

[[pages]]
path = "./src/pages/api.py"
name = "Deployment"
icon = "âš™ï¸"