[[pages]]
path = "server.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/upload.py"
name = "Upload Data"
icon = "ğŸ—„ï¸"

[[pages]]
path = "pages/eda.py"
name = "EDA"
icon = "ğŸ“Š"

[[pages]]
path = "pages/automl.py"
name = "AutoML Training"
icon = "ğŸ¤–"

[[pages]]
path = "pages/preview.py"
name = "Predictions"
icon = "ğŸ”"

[[pages]]
path = "pages/api.py"
name = "Deployment"
icon = "âš™ï¸"