[[pages]]
path = "./sites/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "./sites/upload.py"
name = "Upload Data"
icon = "ğŸ—„ï¸"

[[pages]]
path = "./sites/eda.py"
name = "EDA"
icon = "ğŸ“Š"

[[pages]]
path = "./sites/automl.py"
name = "AutoML Training"
icon = "ğŸ¤–"

[[pages]]
path = "./sites/preview.py"
name = "Predictions"
icon = "ğŸ”"

[[pages]]
path = "./sites/api.py"
name = "Deployment"
icon = "âš™ï¸"